const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Mercurial Superfly',
      category: 'Nike',
      image: '/images/product1.png',
      price: 320,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Boot',
      category: 'Adidas',
      image: '/images/product1.png',
      price: 350,
      rating: 4,
      numReviews: 12,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Mercurial Superfly',
      category: 'Nike',
      image: '/images/product1.png',
      price: 320,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Puma boot',
      category: 'Puma',
      image: '/images/product1.png',
      price: 260,
      rating: 3.5,
      numReviews: 5,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Nike Mercurial Superfly',
      category: 'Nike',
      image: '/images/product1.png',
      price: 320,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}
export default data
